[package]
name = "bbt-net"
publish = false
version = "0.2.0-alpha.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
bbt-agent = { path = "../bbt-agent" }
serde.workspace = true
serde_json.workspace = true
