[package]
name = "bbt-proc"
publish = false
version = "0.2.0-alpha.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
bbt-agent = { path = "../bbt-agent" }
bbt-core = { path = "../bbt-core" }
serde.workspace = true
serde_json.workspace = true
libc = "0.2"

[dev-dependencies]
tempfile = "3"
